# Generated by Django 3.2.7 on 2021-09-09 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atracao',
            options={'verbose_name': 'atração', 'verbose_name_plural': 'atrações'},
        ),
    ]
